[package]
name = "GCJ-2022R2"
version = "0.1.0"
authors = ["Hiroshi Kori <hiroshi.maybe@gmail.com>"]
edition = "2018"

[dependencies]
rand = { version = "=0.7.3", features = ["small_rng"] }
[[bin]]
name = "spiraling_into_control"
path = "spiraling_into_control.rs"

